services:
  node:
    build: .
    ports:
      - "${NODE_PORT:-5000}:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/starwarstl?directConnection=true&replicaSet=rs0
      - REDIS_URI=redis://redis:6379
      - PORT=5000
      - NODE_ENV=${NODE_ENV:-dev}
    depends_on:
      - redis
      - mongodb

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  mongodb:
    image: mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongoInit.js:/docker-entrypoint-initdb.d/init.js
    command:
      ["--quiet", "--replSet", "rs0", "--bind_ip_all", "--logpath", "/dev/null"]
    healthcheck:
      test: >
        bash -c "
        mongosh --eval 'db.adminCommand(\"ping\")' || exit 1;
        mongosh --eval 'rs.status().ok' | grep '1' || exit 1;
        "
      interval: 10s
      timeout: 5s
      retries: 5
    # healthcheck:
    #   test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

volumes:
  mongodb_data:
